import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import AdminToggle from './AdminToggle';
import { Trophy } from 'lucide-react';
const Layout = ({ children, currentTab, onTabSelect, tournament, isAdmin, onAdminToggle, isAuthenticated, onLoginClick, onLogout, }) => {
    return (_jsxs("div", { className: "min-h-screen flex flex-col p-4 space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center space-x-4", children: [isAuthenticated && (_jsx(AdminToggle, { isAdminMode: isAdmin, onToggle: onAdminToggle })), _jsx("span", { className: "ml-2 text-lg font-medium text-gray-700", children: tournament?.name || 'No Tournament Selected' }), tournament && _jsx(Trophy, { className: "ml-2 text-yellow-500" })] }), _jsx("div", { children: !isAuthenticated ? (_jsx("button", { onClick: onLoginClick, className: "bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700", children: "Admin Login" })) : (_jsx("button", { onClick: onLogout, className: "bg-gray-600 text-white px-4 py-2 rounded hover:bg-gray-700", children: "Logout" })) })] }), _jsxs("nav", { className: "bg-gray-200 p-2 flex space-x-4 rounded", children: [['home', 'teams', 'schedule', 'standings', 'bestPlayers'].map((tab) => (_jsx("div", { className: `cursor-pointer px-3 py-1 rounded ${currentTab === tab ? 'bg-primary-600 text-white' : 'hover:bg-gray-300'}`, onClick: () => onTabSelect(tab), children: tab === 'home' ? 'Home' :
                            tab === 'bestPlayers' ? 'Best Players' :
                                tab.charAt(0).toUpperCase() + tab.slice(1) }, tab))), isAdmin && (_jsx("div", { className: `cursor-pointer px-3 py-1 rounded ${currentTab === 'tournaments' ? 'bg-primary-600 text-white' : 'hover:bg-gray-300'}`, onClick: () => onTabSelect('tournaments'), children: "Tournaments" }))] }), _jsx("main", { className: "flex-1 container mx-auto p-4", children: children })] }));
};
export default Layout;
