import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import AdminToggle from './AdminToggle';
import { Trophy } from 'lucide-react';
const Layout = ({ children, currentTab, onTabSelect, tournament, isAdmin, onAdminToggle, isAuthenticated, onLoginClick, onLogout, }) => {
    return (_jsxs("div", { className: "min-h-screen flex flex-col", children: [_jsx("div", { className: "sticky top-0 z-50 bg-white shadow-lg border-b border-gray-200", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 py-3", children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsxs("div", { className: "flex items-center space-x-4", children: [isAuthenticated && (_jsx(AdminToggle, { isAdminMode: isAdmin, onToggle: onAdminToggle })), _jsxs("div", { className: "flex items-center space-x-2", children: [_jsx("span", { className: "text-lg font-semibold text-gray-800", children: tournament?.name || 'No Tournament Selected' }), tournament && _jsx(Trophy, { className: "text-yellow-500 w-5 h-5" })] })] }), _jsx("div", { children: !isAuthenticated ? (_jsx("button", { onClick: onLoginClick, className: "bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors duration-200 text-sm font-medium", children: "Admin Login" })) : (_jsx("button", { onClick: onLogout, className: "bg-gray-600 text-white px-4 py-2 rounded-lg hover:bg-gray-700 transition-colors duration-200 text-sm font-medium", children: "Logout" })) })] }), _jsxs("nav", { className: "bg-gray-100 p-1 flex space-x-1 rounded-lg", children: [['home', 'teams', 'schedule', 'standings', 'bestPlayers'].map((tab) => (_jsx("div", { className: `cursor-pointer px-3 py-2 rounded-md text-sm font-medium transition-colors duration-200 ${currentTab === tab
                                        ? 'bg-blue-600 text-white shadow-sm'
                                        : 'text-gray-700 hover:bg-gray-200 hover:text-gray-900'}`, onClick: () => onTabSelect(tab), children: tab === 'home' ? 'Home' :
                                        tab === 'bestPlayers' ? 'Best Players' :
                                            tab.charAt(0).toUpperCase() + tab.slice(1) }, tab))), isAdmin && (_jsx("div", { className: `cursor-pointer px-3 py-2 rounded-md text-sm font-medium transition-colors duration-200 ${currentTab === 'tournaments'
                                        ? 'bg-blue-600 text-white shadow-sm'
                                        : 'text-gray-700 hover:bg-gray-200 hover:text-gray-900'}`, onClick: () => onTabSelect('tournaments'), children: "Tournaments" }))] })] }) }), _jsx("main", { className: "flex-1 container mx-auto p-4", children: children })] }));
};
export default Layout;
