"""add_is_current_to_tournaments

Revision ID: 9af26445c0c9
Revises: f72ebf8f9608
Create Date: 2025-07-26 19:07:49.326035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af26445c0c9'
down_revision = 'f72ebf8f9608'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###